"""empty message

Revision ID: 5d8b60bb53f7
Revises: 92240b3bd8e9
Create Date: 2022-08-19 10:58:43.874290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d8b60bb53f7'
down_revision = '92240b3bd8e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('Artist_id', sa.Integer(), nullable=False),
    sa.Column('Venue_id', sa.Integer(), nullable=True),
    sa.Column('Venue_name', sa.String(), nullable=True),
    sa.Column('Artist_name', sa.String(), nullable=True),
    sa.Column('Artist_image_link', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['Venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('Artist_id')
    )
    op.drop_table('Shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Shows',
    sa.Column('Artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('Venue_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Venue_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Artist_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Artist_image_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Artist_id'], ['Artist.id'], name='Shows_Artist_id_fkey'),
    sa.ForeignKeyConstraint(['Venue_id'], ['Venue.id'], name='Shows_Venue_id_fkey')
    )
    op.drop_table('Show')
    # ### end Alembic commands ###
