"""empty message

Revision ID: 92240b3bd8e9
Revises: f99db312217c
Create Date: 2022-08-19 09:58:07.114823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92240b3bd8e9'
down_revision = 'f99db312217c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
