"""empty message

Revision ID: 9bf098f3f1fc
Revises: 3eed2214225d
Create Date: 2022-08-17 04:08:57.046945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9bf098f3f1fc'
down_revision = '3eed2214225d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('satrt time', sa.DateTime(), nullable=True))
    op.drop_column('Shows', 'satrt_time')
    op.add_column('Venue', sa.Column('genres', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    op.add_column('Shows', sa.Column('satrt_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('Shows', 'satrt time')
    # ### end Alembic commands ###
