"""empty message

Revision ID: da88e36c78db
Revises: 9bf098f3f1fc
Create Date: 2022-08-18 00:17:42.728272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da88e36c78db'
down_revision = '9bf098f3f1fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.drop_column('Shows', 'satrt_time')
    op.add_column('Venue', sa.Column('genres', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    op.add_column('Shows', sa.Column('satrt_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('Shows', 'start_time')
    # ### end Alembic commands ###
