"""empty message

Revision ID: f99db312217c
Revises: da88e36c78db
Create Date: 2022-08-18 03:17:09.514222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f99db312217c'
down_revision = 'da88e36c78db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('Venue_id', sa.Integer(), nullable=True))
    op.add_column('Shows', sa.Column('Venue_name', sa.String(), nullable=True))
    op.add_column('Shows', sa.Column('Artist_name', sa.String(), nullable=True))
    op.add_column('Shows', sa.Column('Artist_image_link', sa.String(), nullable=True))
    op.drop_constraint('Shows_venue_id_fkey', 'Shows', type_='foreignkey')
    op.create_foreign_key(None, 'Shows', 'Venue', ['Venue_id'], ['id'])
    op.drop_column('Shows', 'venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Shows', type_='foreignkey')
    op.create_foreign_key('Shows_venue_id_fkey', 'Shows', 'Venue', ['venue_id'], ['id'])
    op.drop_column('Shows', 'Artist_image_link')
    op.drop_column('Shows', 'Artist_name')
    op.drop_column('Shows', 'Venue_name')
    op.drop_column('Shows', 'Venue_id')
    # ### end Alembic commands ###
